version: '3.9'


services:
  bot:
    container_name: blacklist
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/blacklist_app
    ports:
      - 5002:5002